# Generated by Django 5.0.3 on 2024-03-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='health',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='user',
        ),
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='health_history',
            field=models.CharField(choices=[('None', 'None'), ('Hypertension', 'Hypertension'), ('Diabetes', 'Diabetes'), ('Asthma', 'Asthma'), ('Heart Disease', 'Heart Disease'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='BloodDonation',
        ),
    ]
