# Generated by Django 5.0.4 on 2024-04-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_hospital_location_donor_hospital_hospital_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='location',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
