# Generated by Django 5.0.4 on 2024-04-07 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_hospital_location_donor_hospital_hospital_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donors.location'),
        ),
    ]
