# Generated by Django 5.0.4 on 2024-04-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_donor_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='location',
        ),
    ]
