# Generated by Django 5.0.4 on 2024-04-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_remove_donor_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='hospital',
        ),
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donors.location'),
        ),
    ]
