# Generated by Django 5.0.4 on 2024-04-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_remove_donor_hospital_donor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
